spring:
  profiles:
    # 环境标识，本机开发环境有意义,如果觉得污染,可以IDEA 传入--spring.profiles.active=local
    active: local
    include: db,rbac
  lifecycle:
    timeout-per-shutdown-phase: 30s
  application:
    name: admin-server
  threads:
    virtual:
      enabled: true
  task:
    scheduling:
      pool:
        size: 1
      thread-name-prefix: event-scheduling-
server:
  port: 8080
  shutdown: graceful
  tomcat:
    remoteip:
      host-header: X-Forwarded-Host
    basedir: .
    connection-timeout: 60s
    threads:
      max: 2000
    accesslog:
      # %h %l %u %t %r %s %b 默认
      #pattern see https://tomcat.apache.org/tomcat-9.0-doc/config/valve.html#Access_Logging
      pattern: '%{X-Forwarded-For}i %h %l %u %t %r %s %b %D'
      enabled: true
      max-days: 2
  forward-headers-strategy: framework
# swagger-ui.html
springdoc:
  api-docs:
    # 默认是true,关闭选择false
    enabled: false