# product environment use application.properties
# don't pulish
server.tomcat.accesslog.enabled=false
server.tomcat.basedir=
springdoc.api-docs.enabled=true
# need pulish
# base
# DB
### meta ###
datasource.meta.host=127.0.0.1
datasource.meta.port=3306
datasource.meta.username=root
datasource.meta.password=12345678
### meta ###
datasource.history.host=127.0.0.1
datasource.history.port=3306
datasource.history.username=root
datasource.history.password=12345678
# login
app.login.session-timeout=2h
# cors
app.cors.enable=true

