# don't publish
server.tomcat.accesslog.enabled=false
server.tomcat.basedir=
springdoc.api-docs.enabled=true
app.cors.enable=true
# DB
db.host=127.0.0.1
db.port=3306
db.user=root
db.password=12345678
# app
app.secret-key=7fG9pL2qKx4Rz1wN18yV3bH5cD6jM0n2
app.wx.app-id=xx
app.wx.app-secret=xxx
app.login.access-token-expire=2h
app.login.refresh-token-expire=3d
